[package]
name = "test_util"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
fail = "0.3"
rand = "0.7"
rand_isaac = "0.2"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv_util = { path = "../tikv_util" }
time = "0.1"
grpcio = { version = "0.5", default-features = false, features = ["openssl-vendored"] }
