[package]
name = "sst_importer"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "external_storage/protobuf-codec",
  "grpcio/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "external_storage/prost-codec",
  "grpcio/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
crc32fast = "1.2"
engine_traits = { path = "../engine_traits" }
external_storage = { path = "../external_storage" }
futures = "0.1"
futures-executor = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
grpcio = { version = "0.5", default-features = false, features = ["openssl-vendored"] }
hex = "0.4"
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
prometheus = { version = "0.8", default-features = false }
quick-error = "1.2.2"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
tokio-sync = "0.1.7"
txn_types = { path = "../txn_types" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[dev-dependencies]
tempfile = "3.0"
test_sst_importer = { path = "../test_sst_importer" }
