[package]
name = "test_sst_importer"
version = "0.1.0"
edition = "2018"
publish = false
description = "test helpers for sst_importer"

[lib]
test = false

[features]
protobuf-codec = [
  "engine/protobuf-codec",
  "engine_rocks/protobuf-codec",
  "keys/protobuf-codec",
  "kvproto/protobuf-codec",
]
prost-codec = [
  "engine/prost-codec",
  "engine_rocks/prost-codec",
  "keys/prost-codec",
  "kvproto/prost-codec",
]

[dependencies]
crc32fast = "1.2"
engine = { path = "../engine" }
engine_rocks = { path = "../engine_rocks" }
engine_traits = { path = "../engine_traits" }
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
