[package]
name = "external_storage"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = ["kvproto/protobuf-codec"]
prost-codec = ["kvproto/prost-codec"]

[dependencies]
futures = "0.3.1"
futures-executor = "0.3"
futures-io = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
rand = "0.7"
rusoto_core = "0.43.0"
rusoto_s3 = "0.43.0"
rusoto_util = { path = "../rusoto_util" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv_alloc = { path = "../tikv_alloc" }
tokio = "0.2.13"
url = "2.0"
bytes = "0.5.3"

[dev-dependencies]
structopt = "0.3"
rusoto_mock = "0.43.0"
tempfile = "3.1"
rust-ini = "0.14.0"
