[package]
name = "test_storage"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "raftstore/protobuf-codec",
  "test_raftstore/protobuf-codec",
  "tikv/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "raftstore/prost-codec",
  "test_raftstore/prost-codec",
  "tikv/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
futures = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raftstore = { path = "../raftstore" }
test_raftstore = { path = "../test_raftstore" }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
txn_types = { path = "../txn_types" }
