[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "kvproto/protobuf-codec",
  "test_storage/protobuf-codec",
  "tidb_query_datatype/protobuf-codec",
  "tikv/protobuf-codec",
  "tipb/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "kvproto/prost-codec",
  "test_storage/prost-codec",
  "tidb_query_datatype/prost-codec",
  "tikv/prost-codec",
  "tipb/prost-codec",
  "txn_types/prost-codec",
]

[dependencies]
futures = "0.1"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
protobuf = "2"
test_storage = { path = "../test_storage" }
tidb_query_datatype = { path = "../tidb_query_datatype" }
tidb_query_common = { path = "../tidb_query_common" }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
txn_types = { path = "../txn_types" }
